proxy:
  secretToken: "bc602bd57346cb7e79ee8f193019a3020bd76ab565a532d8ca446e67a553b849"
singleuser:
  image:
    name: astroaustin/wallaby-jupyterhub
    tag: v0.2.0
  extraEnv:
    DJANGO_DATABASE_NAME: "sofiadb"
    DJANGO_DATABASE_USER: "admin"
    DJANGO_DATABASE_PASSWORD: "password"
    DJANGO_DATABASE_HOST: "127.0.0.1"
  profileList:
    - display_name: "WALLABY"
      description: "Interact with the WALLABY database in Python through a Jupyter Notebook."
      default: true
    - display_name: "Django Tutorial"
      description: "Introductory tutorial notebook for those who have never used Django."
      kubespawner_override:
        image: astroaustin/jupyter-tutorial
        tag: v0.1.2
