proxy:
  secretToken: "bc602bd57346cb7e79ee8f193019a3020bd76ab565a532d8ca446e67a553b849"
singleuser:
  image:
    name: astroaustin/wallaby-jupyterhub
    tag: v0.2.4
    default_url: 
  # memory:
  #   limit: 32G
  #   guarantee: 16G
  extraEnv:
    DJANGO_DATABASE_NAME: "sofiadb"
    DJANGO_DATABASE_USER: "admin"
    DJANGO_DATABASE_PASSWORD: 
    DJANGO_DATABASE_HOST: 
    DJANGO_SETTINGS_MODULE: "src.api.settings"
    DJANGO_ALLOW_ASYNC_UNSAFE: "True"
    
  profileList:
    - display_name: "WALLABY"
      description: "Interact with the WALLABY database in Python through a Jupyter Notebook."
      default: true
      kubespawner_override:
        default_url: /notebooks/notebook.ipynb
    - display_name: "Django Tutorial"
      description: "Introductory tutorial notebook for those who have never used Django."
      kubespawner_override:
        image: astroaustin/tutorial-jupyterhub
        tag: v0.1.0
        default_url: /notebooks/notebook.ipynb
