proxy:
  secretToken: $SECRET_TOKEN

singleuser:
  defaultUrl: "/lab"
  image:
    name: $IMAGE
    tag: v0.1.0
  extraEnv:
    DJANGO_DATABASE_NAME: $DJANGO_DATABASE_NAME
    DJANGO_DATABASE_USER: $DJANGO_DATABASE_USER
    DJANGO_DATABASE_PASSWORD: $DJANGO_DATABASE_PASSWORD
    DJANGO_DATABASE_HOST: $DJANGO_DATABASE_HOST
    DJANGO_SETTINGS_MODULE: "src.api.settings"
    DJANGO_ALLOW_ASYNC_UNSAFE: "True"
  profileList:
    - display_name: "WALLABY"
      description: "Jupyter Notebook with access to the WALLABY database."
      default: true
      kubespawner_override:
        default_url: /lab/tree/notebook.ipynb

hub:
  cookieSecret: $COOKIE_SECRET
  extraConfig:
    myConfig.py: |
      c.Spawner.cmd=["jupyter-labhub"]
