proxy:
  secretToken: "583f29e0b75d8e292369b941089215e0902ef584797b7ff14bfd3030e1acab49"

singleuser:
  image:
    name: astroaustin/wallaby-jupyterhub
    tag: v0.4.1
  extraEnv:
    DJANGO_DATABASE_NAME: "sofiadb"
    DJANGO_DATABASE_USER: "admin"
    DJANGO_DATABASE_PASSWORD: "admin"
    DJANGO_DATABASE_HOST: "146.118.69.90"
    DJANGO_SETTINGS_MODULE: "src.api.settings"
    DJANGO_ALLOW_ASYNC_UNSAFE: "True"
  profileList:
    - display_name: "WALLABY"
      description: "Empty Jupyter Notebook with access to the WALLABY database."
      default: true
      kubespawner_override:
        default_url: /notebooks/notebook.ipynb
    - display_name: "WALLABY Workflow Example"
      description: "Run through an example WALLABY workflow in the Jupyter Notebook."
      kubespawner_override:
        default_url: /notebooks/workflow.ipynb
    - display_name: "WALLABY Detection Duplication Example"
      description: "A starting point for identifying and resolving duplicate detections in the WALLABY database."
      kubespawner_override:
        default_url: /notebooks/duplicate_detections.ipynb
    - display_name: "Django Tutorial"
      description: "Introductory tutorial notebook for those who have never used Django."
      kubespawner_override:
        image: astroaustin/tutorial-jupyterhub
        tag: v0.1.0
        default_url: /notebooks/notebook.ipynb
  # memory:
  #   limit: 32G
  #   guarantee: 16G

hub:
  cookieSecret: "cd42658cefedce5b28fd2b9f45fca499b9e07ac2cbefdda558a2a2e8faee9859"
  extraConfig:
    myConfig.py: |
      from oauthenticator.generic import GenericOAuthenticator

      realm = 'AusSRC'
      clientid = 'notebook'
      domain = 'auth.aussrc.org'

      c.LocalAuthenticator.create_system_users = True
      c.JupyterHub.authenticator_class = 'oauthenticator.generic.GenericOAuthenticator'
      c.GenericOAuthenticator.login_service = 'Keycloak'
      c.GenericOAuthenticator.authorize_url =  f'https://{domain}/auth/realms/{realm}/protocol/openid-connect/auth'
      c.GenericOAuthenticator.userdata_url = f'https://{domain}/auth/realms/{realm}/protocol/openid-connect/userinfo'
      c.GenericOAuthenticator.token_url = f'https://{domain}/auth/realms/{realm}/protocol/openid-connect/token'
      c.GenericOAuthenticator.oauth_callback_url = 'http://146.118.66.30:8080/hub/oauth_callback'
      c.GenericOAuthenticator.userdata_method = 'GET'
      c.GenericOAuthenticator.userdata_params = {"state": "state"}
      c.GenericOAuthenticator.username_key = "preferred_username"
      c.OAuthenticator.client_id = clientid
      c.OAuthenticator.client_secret = 'c06cfa39-1dd8-46a7-b57c-da5f58cd487e'

  # config:
  #   Authenticator:
  #     allowed_users:
  #       - tobias.westmeier@uwa.edu.au
  #       - kristine.spekkens@gmail.com
  #       - shaoli@bao.ac.cn
  #       - tristan.reynolds@uwa.edu.au
  #   DummyAuthenticator:
  #     password: password
  #   JupyterHub:
  #     authenticator_class: dummy