proxy:
  secretToken: "583f29e0b75d8e292369b941089215e0902ef584797b7ff14bfd3030e1acab49"

singleuser:
  defaultUrl: "/lab"
  image:
    name: astroaustin/wallaby-admin-jupyter
    tag: v0.1.0
  extraEnv:
    DJANGO_DATABASE_NAME: "sofiadb"
    DJANGO_DATABASE_USER: "admin"
    DJANGO_DATABASE_PASSWORD: "admin"
    DJANGO_DATABASE_HOST: "146.118.69.90"
    DJANGO_SETTINGS_MODULE: "src.api.settings"
    DJANGO_ALLOW_ASYNC_UNSAFE: "True"
  profileList:
    - display_name: "WALLABY"
      description: "Empty Jupyter Notebook with access to the WALLABY database."
      default: true
      kubespawner_override:
        default_url: /lab/tree/notebook.ipynb

hub:
  cookieSecret: "cd42658cefedce5b28fd2b9f45fca499b9e07ac2cbefdda558a2a2e8faee9859"
  extraConfig:
    myConfig.py: |
      c.Spawner.cmd=["jupyter-labhub"]
