# Generated by Django 3.1.6 on 2021-02-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('state', models.TextField(max_length=10)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'shops',
            },
        ),
    ]
